language: rust
sudo: false
rust:
  - stable

env:
  global:
    - TRAVIS_TESTING=t
  matrix:
    - EMACS_VERSION=master

install:
  - curl -fSLO https://github.com/npostavs/emacs-travis/releases/download/bins/emacs-bin-${EMACS_VERSION}.tar.gz
  - tar -xaf emacs-bin-${EMACS_VERSION}.tar.gz -C /
  # Configure $PATH: Emacs installed to /tmp/emacs
  - export PATH=/tmp/emacs/bin:${PATH}
  - emacs --version
  # Install RLS
  - rustup update
  - rustup component add rls-preview rust-analysis rust-src
  # Install https://github.com/palantir/python-language-server
  - virtualenv .
  - . ./bin/activate
  - pip install 'python-language-server[all]==0.31.10'
  # Install eclipse.jdt.ls
  - curl -fSL http://download.eclipse.org/jdtls/snapshots/jdt-language-server-latest.tar.gz -o eclipse.tar.gz
  - mkdir eclipse.jdt.ls
  - tar -C eclipse.jdt.ls -xzf eclipse.tar.gz
  - export CLASSPATH=$(pwd)/$(find eclipse.jdt.ls/ -regex eclipse.jdt.ls/plugins/org.eclipse.equinox.launcher_.*.jar):${CLASSPATH}
  # enable ssh to localhost with no password prompt
  - ssh-keygen -t rsa -C "<me@mymail>" -f ~/.ssh/id_this_travis_build -P ""
  - cat ~/.ssh/id_this_travis_build.pub >> ~/.ssh/authorized_keys
  - printf "%s\n" 'Host localhost' '  IdentityFile ~/.ssh/id_this_travis_build' >> ~/.ssh/config
  - ssh -o StrictHostKeyChecking=no localhost echo I can ssh to localhost OK
  # try latest fix from tramp
  - git clone https://git.savannah.gnu.org/git/tramp.git

before_script:
  - make eglot.elc ERROR_ON_WARN=t

script:
  - make check

